### ISSUE TITLE
Problèmes lors de mesure ph et ec en même temps .

### ISSUE THREAD

**Issue by johnx102** [GreenPonik/esp32-read-ph-and-ec-with-ADC-example#1]
Merci pour ce code qui fonctionne a merveille . Néanmoins j'ai un soucis lors du relevé du ph et ec et que les sondes sont dans la meme solutions, les mesures ne sont plus correct, si les sondes sont dans 2 solutions différentes, pas de soucis ... avez vous remarquez cela ?

**Comment by MkLHX** [comment]
Bonjour @johnx102,

Si vos mesures sont perturbées lorsque vous utilisez les deux sondes dans la même solution c'est que vous n'avez pas installé d'isolateur sur votre circuit de mesure. En effet le fait de placer une sonde de pH et une sonde d'EC dans la même eau a pour résultat qu'il y a une perturbation du signal.
Pour éviter cela placer un isolateur sur votre circuit de mesure d'EC.

**Comment by johnx102** [comment]
Merci pour cet réponse , j’en était arrivé à la même conclusion après plusieur recherche et je vien de voir après coup que ce module existais ...
J’ai commandé !! Encore merci pour votre aide  et ce fabuleux projet !!

Envoyé de mon iPhone

**Comment by MkLHX** [comment]
ok donc je ferme l'issue. N’hésitez pas confirmer la correction du problème avec l'ajout de l'isolateur.

**Comment by johnx102** [comment]
Ok je vous ferai  un retour .
Merci encore
