### ISSUE TITLE
intervals run too fast

### ISSUE THREAD

**Issue by samuelchiang** [GreenPonik/esp32-read-ph-and-ec-with-ADC-example#2]
if (now - last[3] >= intervals[3]) //5000ms interval
  {

    last[3] = now; //need to add this line
  }

**Comment by MkLHX** [comment]
????

**Comment by MkLHX** [comment]
this is the best issue i ever seen on github.

Hello can be a good start.

Could you please submit issue with details and what is the code for?

Every Pull Requests are welcome with comments and explainations

Have a nice day.

**Comment by samuelchiang** [comment]
I didn't explain the issue clearly.
Therefore I made a pull request fix #3 for this issue.
Have a nice day, too.

**Comment by MkLHX** [comment]
Hi thank you for your contribution!
I going to reveiw your PR

**Comment by MkLHX** [comment]
it's merged thx!
